version: "3.3"
services:
  db:
    image: postgres:13.4
    command: 
      - -c
      - max_replication_slots=10
      - -c
      - wal_level=logical
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  openehr:
    image: "ehrbase/ehrbase:${EHRBASE_TAG}"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://${POSTGRES_PRIVATE_HOST}:${POSTGRES_PORT}/ehrbase"
      SPRING_DATASOURCE_USERNAME: ehrbase
      SPRING_DATASOURCE_PASSWORD: ehrbase
      SPRING_DATASOURCE_MAX_ACTIVE: 8
      SERVER_AQLCONFIG_USEJSQUERY: "false"
      SERVER_NODENAME: "localhost"
      SECURITY_AUTHTYPE: NONE
      ABAC_ENABLED: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./application.yml:/application.yml
    command: "java -Dspring.config.location=file:/application.yml -jar ehrbase.jar"

  fhir:
    image: "hapiproject/hapi:v5.7.0"
    environment:
      spring.datasource.url: "jdbc:postgresql://${POSTGRES_PRIVATE_HOST}:${POSTGRES_PORT}/hapi"
      spring.datasource.username: hapi
      spring.datasource.password: hapi
      spring.datasource.maxActive: 8
      spring.datasource.driverClassName: org.postgresql.Driver
      hapi.fhir.subscription.resthook_enabled: "true"
      hapi.fhir.subscription.websocket_enabled: "true"
      hapi.fhir.client_id_strategy: ANY
      hapi.fhir.nats: "nats://nats:4222"
  
  caddy:
    image: caddy:${CADDY_TAG}
    ports:
      - "2019:2019"
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-:80}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config


volumes: 
  db-data:
  caddy_data:
  caddy_config:
